import adeniyi1 from "./images/Adeniyi1.jpg";
import adeniyi2 from "./images/Adeniyi2.jpg";
import adeniyi3 from "./images/Adeniyi3.jpg";
import adeniyi4 from "./images/Adeniyi4.jpg";
import adeniyi5 from "./images/Adeniyi5.jpg";
import adeniyi6 from "./images/Adeniyi6.jpg";
import adeniyi7 from "./images/Adeniyi7.jpg";

import img1 from "./images/img1.jpg";
import img3 from "./images/img3.jpg";
import angular from "./images/angular.png";
import bg1 from "./images/bga.jpg";
import blog from "./images/blog.png";
import blog1 from "./images/blog1.png";
import csslogo from "./images/csslogo.png";
import git from "./images/git.png";
import glass from "./images/glass.jpg";
import html from "./images/html.png";
import js from "./images/js.jpg";
import htmlLogo from "./images/LOGOHTML.png";
import manSmall from "./images/man-small.png";
import man from "./images/man.jpg";
import neobg from "./images/neonbg.jpg";
import nodeJs from "./images/nodejs.png";
import pngItem from "./images/PngItem.png";
import portfolio0 from "./images/portfolio.png";
import portfolio1 from "./images/portfolio1.png";
import portfolio2 from "./images/portfolio2.png";
import portfolio3 from "./images/portfolio3.png";
import python from "./images/python.webp";
import reactJs from "./images/reactJS.png";
import react1 from "./images/react1.png";
import sass from "./images/sass.png";
import tree from "./images/tree.jpg";
import vue from "./images/vue.png";
// import whiteLine from "./images/white-line.png";
import wp from "./images/wp.png";

export const Adeniyi1 = adeniyi1;
export const Adeniyi2 = adeniyi2;
export const Adeniyi3 = adeniyi3;
export const Adeniyi4 = adeniyi4;
export const Adeniyi5 = adeniyi5;
export const Adeniyi6 = adeniyi6;
export const Adeniyi7 = adeniyi7;
export const Img1: string = img1;
export const Img3: string = img3;
export const Angular: string = angular;
export const Bg1: string = bg1;
export const Blogg: string = blog;
export const Blog1: string = blog1;
export const Csslogo: string = csslogo;
export const Git: string = git;
export const Glass: string = glass;
export const Html: string = html;
export const Js: string = js;
export const HtmlLogo: string = htmlLogo;
export const ManSmall: string = manSmall;
export const Man: string = man;
export const Neobg: string = neobg;
export const NodeJs: string = nodeJs;
export const PngItem: string = pngItem;
export const Portfolio0: string = portfolio0;
export const Portfolio1: string = portfolio1;
export const Portfolio2: string = portfolio2;
export const Portfolio3: string = portfolio3;
export const Python: string = python;
export const ReactJs: string = reactJs;
export const React1: string = react1;
export const Sass: string = sass;
export const Tree: string = tree;
export const Vue: string = vue;
// export const WhiteLine: string = whiteLine;
export const Wp: string = wp;
